### ISSUE TITLE
vnet-linuxcluster.parameters.json has keys misspelled

### ISSUE THREAD

**Issue by hguanmsft** [microsoft/service-fabric-scripts-and-templates#9]
https://github.com/Azure/service-fabric-scripts-and-templates/blob/master/templates/cluster-tutorial/vnet-linuxcluster.parameters.json

"certificateUrlvalue": {

"sourceVaultvalue": {

The above 'value' should start with upper case 'V', otherwise, 'az sf cluster create' will complain with 

the primary certificate parameters names in the parameters file should be specified with'sourcevaultvalue','certificatethumbprint','certificateurlvalue',if the secondary certificate parameters are specified in the parameters file, the parameters names should be specified with'secsourcevaultvalue','seccertificatethumbprint','seccertificateurlvalue'

**Comment by meisterheister** [comment]
Ran into the same issue and committed a change https://github.com/meisterheister/service-fabric-scripts-and-templates/tree/patch-1

**Comment by erikadoyle** [comment]
Thanks! This has been merged.
